# Azure Pipeline JUST for PR checks

pr:
- main

jobs:

- job: Build
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
        isMac: True
      win:
        imageName: 'windows-2019'
        isWindows: True
      lin:
        imageName: 'ubuntu-20.04'
        isLinux: True

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    fetchDepth: 1

  - bash: |
      cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
      cmake --build build --config Release
      ./build/test-binary/sst-cpputils-tests
    displayName: Run tests with cmake
