name: Build Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build_feature:
    name: Test ${{ matrix.name }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            testExe: build/sst-cpputils-tests

          - os: macos-latest
            name: mac
            testExe: build/sst-cpputils-tests

          - os: windows-latest
            name: win msvc
            testExe: build/Release/sst-cpputils-tests.exe
            cmake-args: -A x64

          - os: windows-latest
            name: win clangcl
            testExe: build/Release/sst-cpputils-tests.exe
            cmake-args: -A x64 -T ClangCL  -G"Visual Studio 17 2022"

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Smoke test
        run: |
          cmake -S . -B ./build ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=Release -DSST_CPPUTILS_BUILD_TESTS=TRUE -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          cmake --build ./build --config Release

      - name: Run Smoke Test
        run: |
          ls ${{ matrix.testExe }}
          ${{ matrix.testExe }}


  build_test_docker:
    name: Test - Docker Ubuntu 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build in Docker
        uses: surge-synthesizer/sst-githubactions/cmake-in-docker@main
        with:
          image: ghcr.io/surge-synthesizer/sst-dockerimages/ubuntu20_gcc11:main
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          cmakeArgs: -DCMAKE_BUILD_TYPE=Release -DSST_CPPUTILS_BUILD_TESTS=TRUE
          target: sst-cpputils-tests

      - name: Run Test
        run: |
          ls -l build
          ./build/sst-cpputils-tests
